### ISSUE TITLE
Subscription stuck in the staging environment. 

### ISSUE THREAD

**Issue by Btod4** [rcl-ssl/docs#22]
Hi.

Having a problem with Lets Encrypt.

Every time i create a new standalone SSL, its being pushed to the Lets Encrypt Staging environment. Thus the cert is invalid. 

The issuer states its Let's Encrypt - STAGING and the cert path links to a root that expired in January. 

Brett

**Comment by rcladmin** [comment]
You can try it now. If you cannot log in , please cancel your subscription and create a new one.
