### ISSUE TITLE
SSL Certificates are not updated automatically

### ISSUE THREAD

**Issue by carloscds** [rcl-ssl/docs#26]
Why my certificates are not update automatically ? I need to update manually every time.

**Comment by carloscds** [comment]
@rcladmin My certificates not update automatic yet. When are you solve this ?

**Comment by rcladmin** [comment]
Sorry for the delay. The new version of the RCL SSL Apps will be officially released on 1st May 2022. This will include an update to the AutoRenew function for Azure App Service.

**Comment by rcladmin** [comment]
The new version of the AutoRenew function (v6.0.10) is available today. You can delete the old AutoRenew function and install the new one. If you encounter errors, please let me know. I will try to resolve it.

https://docs.rclapp.com/autorenew/autorenew.html
https://github.com/rcl-ssl/RCL.AutoRenew.Function
