### ISSUE TITLE
Error to generate certificate

### ISSUE THREAD

**Issue by carloscds** [rcl-ssl/docs#28]
Error:Failed to manually update certificate for host : www.XXX.com of type : Azure App Service for challenge : HTTP. Object reference not set to an instance of an object.. none Help link :
Information:Waiting for process to complete ****

**Comment by rcladmin** [comment]
Try deleting the certificate and re-creating from scratch.

**Comment by carloscds** [comment]
@rcladmin Why ? I have many SSLs, I need to delete and recreate all of them ?

**Comment by rcladmin** [comment]
Only delete and re-create the certificate for the site that has failed the manual update. The rest of sites that has passed the manual updates do not need to be re-created. In the meantime , you can use this approach, until the new version of the AutoRenew app is available.
