### ISSUE TITLE
Key File Download

### ISSUE THREAD

**Issue by agmarkmike** [rcl-ssl/docs#30]
Hi,

I'm unable to download the private key file for my newly created cert.  When clicking the download link, it takes me to a page in the browser with what looks like the certificate text.  I deleted and recreated the certificate with the same result.

**Comment by rcladmin** [comment]
I am looking into this.

**Comment by rcladmin** [comment]
You can try downloading the Certificate Private Key file (.key) now. You do not need to delete and recreate the certificate.
