### ISSUE TITLE
I cant create certificate - URGENT

### ISSUE THREAD

**Issue by carloscds** [rcl-ssl/docs#32]
Error:Could not create App Service certificate : www.xxx.com.br with challenge : HTTP BadRequest : Could not bind the PFX certificate : www.cdsinformatica.com.br to the app service : xxxx. Failure in AzureService in AzureHostnameBindingService : Put. Failed response : NotFound in AzureHostnameBindingService : Put. {"Code":"NotFound","Message":"Cannot find Certificate with name 1618161BA302AF2932DC3F28D226407A298F1870.","Target":null,"Details":[{"Message":"Cannot find Certificate with name 1618161BA302AF2932DC3F28D226407A298F1870."},{"Code":"NotFound"},{"ErrorEntity":{"ExtendedCode":"51004","MessageTemplate":"Cannot find {0} with name {1}.","Parameters":["Certificate","1618161BA302AF2932DC3F28D226407A298F1870"],"Code":"NotFound","Message":"Cannot find Certificate with name 1618161BA302AF2932DC3F28D226407A298F1870."}}],"Innererror":null} . SSL Azure App Service Bind Certificate - RCL V1 API

**Comment by rcladmin** [comment]
looking into this

**Comment by rcladmin** [comment]
Could not reproduce the error on my end. Do you have any security locks on the web app/resource group that are preventing deletes? 

Try creating a new certificate again and see if it throws a delete error. This will give me a clue to try to solve this issue.

**Comment by carloscds** [comment]
@rcladmin I already try to create a new certiface an receive same error.

**Comment by rcladmin** [comment]
try creating or updating several certificates. I need to see if the error messages has changed since a few minutes ago.

**Comment by carloscds** [comment]
@rcladmin, ok but I have error, see my logs. How can I solve this ?

**Comment by rcladmin** [comment]
You need to try creating new certificates or updating your certificates again to see if the log changes. Only then , I can get a clue of what may be causing the problem. I have already seen your existing logs but I need more updated logs to see if there are deletion issues.
